Blast:
  hitlist_size: 1000
  blast_database: pdbaa
  blast_local: False
  length_restrict: False
  length_margin: 0.5
  include_low_identity_seqs: True
  identity_blast: 0.25
  pro_blast_: False
  min_low_identity_seqs: 0
  max_low_identity_seqs: -1
  additional_hits: 2000

Clustering:
  cluster_seqs: False
  identity_cluster: 0.6
  pro_clustering_: False
  identity_cluster_step: 0.02
  min_number_clusters: 50
  max_number_clusters: 300

Pfam domains:
  check_pfam_domains: False

Alignment:
  align_seqs: False
  trim: False

Weblogo:
  generate_logo: False
  weblogo_format: png

Tree:
  generate_tree: False
  tree_type: NJ
  bootstrap_replications: 100

Outputs:
  output_dir: ""
