# -*- coding: utf-8 -*-
"""ProContext.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jS-MUXL1eRY8NErmYEXEdpYx9XrnXH6w
"""

## ProContext Module

#This module is intended to provide the genomical neighborhood of the query protein

import matplotlib.pyplot as plt
import matplotlib.patches as patches
from Bio import Entrez, SeqIO
import os

def genetic_neighborhood(protein_id: str, outputs_dir:str):
    # Using a generic email for Entrez
    Entrez.email = "your.email@example.com"

    # Fetch protein record to get nucleotide accession
    try:
        handle = Entrez.efetch(
            db="protein",
            id=protein_id,
            rettype="gb",
            retmode="text"
        )
        record = SeqIO.read(handle, "genbank")
        handle.close()
    except Exception as e:
        print(f"Error fetching protein record for {protein_id}: {e}")
        return

    nucleotide_accession = None
    for feature in record.features:
        if feature.type == "CDS" and "coded_by" in feature.qualifiers:
            coded_by_value = feature.qualifiers['coded_by'][0]
            coded_by_value = coded_by_value.replace("complement(", "").replace(")", "")
            nucleotide_accession = coded_by_value.split(':')[0]
            break

    if not nucleotide_accession:
        print(f"Could not find nucleotide accession for protein {protein_id}")
        return

    # Fetch genomic record
    try:
        handle = Entrez.efetch(
            db="nucleotide",
            id=nucleotide_accession,
            rettype="gb",
            retmode="text"
        )
        genome_record = SeqIO.read(handle, "genbank")
        handle.close()
    except Exception as e:
        print(f"Error fetching genome record for {nucleotide_accession}: {e}")
        return

    # Get CDS features from the genome record
    cds_features = [f for f in genome_record.features if f.type == "CDS"]

    # Find the target protein's index
    target_cds_index = -1
    for i, cds in enumerate(cds_features):
        if "protein_id" in cds.qualifiers and protein_id in cds.qualifiers["protein_id"]:
            target_cds_index = i
            break

    if target_cds_index == -1:
        print(f"Target protein {protein_id} not found within genome CDS features.")
        return

    # Extract neighbors (5 before, 5 after, including the target)
    start_index = max(0, target_cds_index - 5)
    end_index = min(len(cds_features), target_cds_index + 6)
    neighbors_to_visualize = cds_features[start_index:end_index]

    if not neighbors_to_visualize:
        print("No neighboring CDS features to visualize.")
        return

    # Determine coordinates for plotting
    min_coord = min(int(f.location.start) for f in neighbors_to_visualize)
    max_coord = max(int(f.location.end) for f in neighbors_to_visualize)

    fig, ax = plt.subplots(figsize=(15, 9)) # Increased figure height for more label space

    y_pos = 0 # All features will be on the same horizontal line for simplicity

    for i, cds in enumerate(neighbors_to_visualize):
        start = int(cds.location.start)
        end = int(cds.location.end)
        strand = cds.location.strand

        locus_tag_val = cds.qualifiers.get("locus_tag", [""])[0]
        protein_id_val = cds.qualifiers.get("protein_id", [""])[0]
        product_val = cds.qualifiers.get("product", [""])[0]

        # Construct the identifier part of the label
        id_parts = []
        if locus_tag_val:
            id_parts.append(locus_tag_val)
        if protein_id_val and protein_id_val not in id_parts: # Avoid duplication if locus_tag is similar to protein_id
            id_parts.append(protein_id_val)

        id_label = " | ".join(id_parts) if id_parts else "Unknown ID"

        # Create a shortened product description if it exists
        product_display = ""
        if product_val:
            words = product_val.split(' ')
            if len(words) > 4: # Shorten if more than 4 words for better fit
                product_display = " ".join(words[:4]) + "..."
            else:
                product_display = product_val

        # Combine into a single label string for inside the rectangle
        label_lines = []
        if id_label: label_lines.append(id_label)
        if product_display: label_lines.append(product_display)

        label = "\n".join(label_lines) if label_lines else "Unknown"

        color = "#F5C710" if i == (target_cds_index - start_index) else "#D3D3D3" # Highlight target protein

        # Draw the feature as a rectangle
        ax.add_patch(patches.Rectangle((start, y_pos - 0.2), end - start, 0.4, facecolor=color, edgecolor='black', zorder=2))

        # Place text inside the rectangle
        text_x = start + (end - start) / 2
        text_y = y_pos # Center vertically within the rectangle

        # Dynamically adjust fontsize and rotation based on feature length and label length
        feature_length = end - start

        current_fontsize = 7
        current_rotation = 45 # Default to 45 degrees

        # A rough heuristic: if the feature is short or label is long, rotate more or use smaller font
        if len(label) * current_fontsize > feature_length / 2: # If label is too long relative to feature
            current_rotation = 90 # Rotate for vertical reading
            current_fontsize = 6

        ax.text(text_x, text_y, label, ha='center', va='center',
                fontsize=current_fontsize, rotation=current_rotation, color='black')

    ax.set_xlim(min_coord - 100, max_coord + 100) # Add some padding
    ax.set_ylim(-1.2, 1.2) # Adjusted y-limits for more space to prevent label clipping if rotated
    ax.set_yticks([]) # Hide y-axis
    ax.set_xlabel("Nucleotide Position")
    ax.set_title(f"Genetic Neighborhood of {protein_id} (simplified view)")
    plt.grid(axis='x', linestyle='--', alpha=0.7)
    plt.tight_layout()

    # Save the plot as a PDF
    pdf_filename = os.path.join(outputs_dir, f"{protein_id}_neighborhood.pdf")
    plt.savefig(pdf_filename, format='pdf')
    print(f"Plot saved to {pdf_filename}")

    plt.show()